apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-test
  name: nginx-test
  namespace: default
spec:
  containers:
  - image: nginx:alpine
    imagePullPolicy: IfNotPresent
    name: nginx-test
    resources: {}
